baseURL = "https://yh-max.github.io/"
defaultContentLanguage = "en"
title = "Yan Han"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
author = "Yan Han"
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowPostNavLinks = true

[[menu.main]]
name = "Algorithms"
url = "/algorithms/"
weight = 1

[[menu.main]]
name = "Computer Vision"
url = "/computer-vision/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3

[[menu.main]]
name = "Research"
url = "/research/"
weight = 4